timeout: 120m
steps:
    - id: 'tf init'
      dir: 'projects-init'
      name: 'hashicorp/terraform:1.0.7'
      entrypoint: 'sh'
      args: 
      - '-c'
      - |
          terraform init -reconfigure --backend-config="bucket=project-init"

    - id: 'tf plan'
      dir: 'projects-init'
      name: 'hashicorp/terraform:1.0.7'
      entrypoint: 'sh'
      args: 
      - '-c'
      - | 
          terraform plan -lock=false || exit 1
